/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.amaisov.interfazteclado;

/**
 *
 * @author amairani
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    public Grafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantalla = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        esc = new javax.swing.JButton();
        esclamacion = new javax.swing.JButton();
        tabulador = new javax.swing.JButton();
        ctrl = new javax.swing.JButton();
        shift = new javax.swing.JButton();
        mayusculas = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        w = new javax.swing.JButton();
        r = new javax.swing.JButton();
        e = new javax.swing.JButton();
        u = new javax.swing.JButton();
        i = new javax.swing.JButton();
        y = new javax.swing.JButton();
        t = new javax.swing.JButton();
        parentesis = new javax.swing.JButton();
        parentesis2 = new javax.swing.JButton();
        p = new javax.swing.JButton();
        o = new javax.swing.JButton();
        q = new javax.swing.JButton();
        ene = new javax.swing.JButton();
        f = new javax.swing.JButton();
        h = new javax.swing.JButton();
        a = new javax.swing.JButton();
        l = new javax.swing.JButton();
        k = new javax.swing.JButton();
        d = new javax.swing.JButton();
        dospuntos = new javax.swing.JButton();
        s = new javax.swing.JButton();
        comillas = new javax.swing.JButton();
        j = new javax.swing.JButton();
        g = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        n = new javax.swing.JButton();
        slash = new javax.swing.JButton();
        c = new javax.swing.JButton();
        m = new javax.swing.JButton();
        b = new javax.swing.JButton();
        x = new javax.swing.JButton();
        v = new javax.swing.JButton();
        interrogacion = new javax.swing.JButton();
        coma = new javax.swing.JButton();
        z = new javax.swing.JButton();
        shift2 = new javax.swing.JButton();
        ctrl2 = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        alt = new javax.swing.JButton();
        alt2 = new javax.swing.JButton();
        puntoycoma = new javax.swing.JButton();
        spacebar = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        derecha = new javax.swing.JButton();
        abajo = new javax.swing.JButton();
        izquierda = new javax.swing.JButton();
        arriba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pantalla.setColumns(20);
        pantalla.setRows(5);
        jScrollPane1.setViewportView(pantalla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setOpaque(false);

        esc.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        esc.setText("Esc");
        esc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escActionPerformed(evt);
            }
        });

        esclamacion.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        esclamacion.setText("!");
        esclamacion.setOpaque(true);
        esclamacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esclamacionActionPerformed(evt);
            }
        });

        tabulador.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tabulador.setText("Tab");
        tabulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabuladorActionPerformed(evt);
            }
        });

        ctrl.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        ctrl.setText("Ctrl");
        ctrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlActionPerformed(evt);
            }
        });

        shift.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        shift.setText("Shift");
        shift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shiftMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shiftMouseEntered(evt);
            }
        });
        shift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftActionPerformed(evt);
            }
        });

        mayusculas.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        mayusculas.setLabel("Mayus");
        mayusculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mayusculasMouseClicked(evt);
            }
        });
        mayusculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayusculasActionPerformed(evt);
            }
        });

        uno.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        uno.setText("1");
        uno.setOpaque(true);
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        dos.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        dos.setText("2");
        dos.setOpaque(true);
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        cuatro.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cuatro.setText("4");
        cuatro.setOpaque(true);
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        tres.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tres.setText("3");
        tres.setOpaque(true);
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        siete.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        siete.setText("7");
        siete.setOpaque(true);
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        ocho.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        ocho.setText("8");
        ocho.setOpaque(true);
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        seis.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        seis.setText("6");
        seis.setOpaque(true);
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        cinco.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cinco.setText("5");
        cinco.setOpaque(true);
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        suma.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        suma.setText("+");
        suma.setOpaque(true);
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        resta.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        resta.setText("-");
        resta.setOpaque(true);
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        cero.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cero.setText("0");
        cero.setOpaque(true);
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        nueve.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        nueve.setText("9");
        nueve.setOpaque(true);
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        borrar.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        borrar.setText("<---");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        w.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        w.setText("W");
        w.setOpaque(true);
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });

        r.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        r.setText("R");
        r.setOpaque(true);
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        e.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        e.setText("E");
        e.setOpaque(true);
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        u.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        u.setText("U");
        u.setOpaque(true);
        u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uActionPerformed(evt);
            }
        });

        i.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        i.setText("I");
        i.setOpaque(true);
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });

        y.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        y.setText("Y");
        y.setOpaque(true);
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });

        t.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        t.setText("T");
        t.setOpaque(true);
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });

        parentesis.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        parentesis.setText(")");
        parentesis.setOpaque(true);
        parentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisActionPerformed(evt);
            }
        });

        parentesis2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        parentesis2.setText("(");
        parentesis2.setOpaque(true);
        parentesis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesis2ActionPerformed(evt);
            }
        });

        p.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        p.setText("P");
        p.setOpaque(true);
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        o.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        o.setText("O");
        o.setOpaque(true);
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });

        q.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        q.setText("Q");
        q.setOpaque(true);
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });

        ene.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        ene.setText("Ñ");
        ene.setActionCommand("ene");
        ene.setOpaque(true);
        ene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eneActionPerformed(evt);
            }
        });

        f.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        f.setText("F");
        f.setOpaque(true);
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        h.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        h.setText("H");
        h.setOpaque(true);
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });

        a.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        a.setText("A");
        a.setOpaque(true);
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        l.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        l.setText("L");
        l.setOpaque(true);
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });

        k.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        k.setText("K");
        k.setOpaque(true);
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });

        d.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        d.setText("D");
        d.setOpaque(true);
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        dospuntos.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        dospuntos.setText(":");
        dospuntos.setOpaque(true);
        dospuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dospuntosActionPerformed(evt);
            }
        });

        s.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        s.setText("S");
        s.setOpaque(true);
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        comillas.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        comillas.setText("\"");
        comillas.setOpaque(true);
        comillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comillasActionPerformed(evt);
            }
        });

        j.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        j.setText("J");
        j.setOpaque(true);
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });

        g.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        g.setText("G");
        g.setOpaque(true);
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        punto.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        punto.setText(".");
        punto.setOpaque(true);
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        n.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        n.setText("N");
        n.setOpaque(true);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        slash.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        slash.setText("/");
        slash.setOpaque(true);
        slash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slashActionPerformed(evt);
            }
        });

        c.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        c.setText("C");
        c.setOpaque(true);
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        m.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        m.setText("M");
        m.setOpaque(true);
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        b.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        b.setText("B");
        b.setOpaque(true);
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        x.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        x.setText("X");
        x.setOpaque(true);
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        v.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        v.setText("V");
        v.setOpaque(true);
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        interrogacion.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        interrogacion.setText("?");
        interrogacion.setOpaque(true);
        interrogacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interrogacionActionPerformed(evt);
            }
        });

        coma.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        coma.setText(",");
        coma.setOpaque(true);
        coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comaActionPerformed(evt);
            }
        });

        z.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        z.setText("Z");
        z.setOpaque(true);
        z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zActionPerformed(evt);
            }
        });

        shift2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        shift2.setText("Shift");
        shift2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shift2MouseClicked(evt);
            }
        });
        shift2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shift2ActionPerformed(evt);
            }
        });

        ctrl2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        ctrl2.setText("Ctrl");
        ctrl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrl2ActionPerformed(evt);
            }
        });

        igual.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        igual.setText("=");
        igual.setOpaque(true);
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        alt.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        alt.setText("alt");
        alt.setOpaque(true);
        alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altActionPerformed(evt);
            }
        });

        alt2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        alt2.setText("alt");
        alt2.setOpaque(true);
        alt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt2ActionPerformed(evt);
            }
        });

        puntoycoma.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        puntoycoma.setText(";");
        puntoycoma.setOpaque(true);
        puntoycoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoycomaActionPerformed(evt);
            }
        });

        spacebar.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        spacebar.setText("Space Bar");
        spacebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spacebarActionPerformed(evt);
            }
        });

        enter.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        enter.setText("enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        derecha.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        derecha.setText("<");
        derecha.setOpaque(true);
        derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechaActionPerformed(evt);
            }
        });

        abajo.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        abajo.setText("v");
        abajo.setOpaque(true);
        abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abajoActionPerformed(evt);
            }
        });

        izquierda.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        izquierda.setText(">");
        izquierda.setOpaque(true);
        izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierdaActionPerformed(evt);
            }
        });

        arriba.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        arriba.setText("^");
        arriba.setOpaque(true);
        arriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arribaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ctrl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spacebar, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(shift, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(interrogacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(slash, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shift2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(puntoycoma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctrl2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(esclamacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(tabulador, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(parentesis2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(parentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(mayusculas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ene, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dospuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comillas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(esclamacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tabulador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(o, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parentesis2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mayusculas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ene, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dospuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comillas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(enter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shift, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(interrogacion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slash, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shift2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctrl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puntoycoma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spacebar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctrl2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(arriba, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(derecha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escActionPerformed
 pantalla.setText("");        
    // TODO add your handling code here:
    }//GEN-LAST:event_escActionPerformed

    private void esclamacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esclamacionActionPerformed
 pantalla.setText(pantalla.getText() + esclamacion.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_esclamacionActionPerformed

    private void tabuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabuladorActionPerformed
 pantalla.setText(pantalla.getText() +"        ");        
    // TODO add your handling code here:
    }//GEN-LAST:event_tabuladorActionPerformed

    private void ctrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlActionPerformed
 pantalla.setText(pantalla.getText() + ctrl.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_ctrlActionPerformed

    private void shiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftActionPerformed
         
    // TODO add your handling code here:
    }//GEN-LAST:event_shiftActionPerformed

    private void mayusculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayusculasActionPerformed
    
    }//GEN-LAST:event_mayusculasActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        pantalla.setText(pantalla.getText() + uno.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        pantalla.setText(pantalla.getText() + dos.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_dosActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        pantalla.setText(pantalla.getText() + cuatro.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_cuatroActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
             pantalla.setText(pantalla.getText() + tres.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_tresActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        pantalla.setText(pantalla.getText() + siete.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        pantalla.setText(pantalla.getText() + ocho.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_ochoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        pantalla.setText(pantalla.getText() + seis.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_seisActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        pantalla.setText(pantalla.getText() + cinco.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_cincoActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
 pantalla.setText(pantalla.getText() + suma.getText());       
    // TODO add your handling code here:
    }//GEN-LAST:event_sumaActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
 pantalla.setText(pantalla.getText() + resta.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_restaActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        pantalla.setText(pantalla.getText() + cero.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_ceroActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        pantalla.setText(pantalla.getText() + nueve.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_nueveActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        String text = pantalla.getText();
        pantalla.setText(text.substring(0, text.length() - 1));
    }//GEN-LAST:event_borrarActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        pantalla.setText(pantalla.getText() + w.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_wActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        pantalla.setText(pantalla.getText() + r.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_rActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        pantalla.setText(pantalla.getText() + e.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_eActionPerformed

    private void uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uActionPerformed
        pantalla.setText(pantalla.getText() + u.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_uActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        pantalla.setText(pantalla.getText() + i.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        pantalla.setText(pantalla.getText() + y.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_yActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        pantalla.setText(pantalla.getText() + t.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_tActionPerformed

    private void parentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisActionPerformed
 pantalla.setText(pantalla.getText() + parentesis.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_parentesisActionPerformed

    private void parentesis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesis2ActionPerformed
 pantalla.setText(pantalla.getText() + parentesis2.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_parentesis2ActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        pantalla.setText(pantalla.getText() + p.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
        pantalla.setText(pantalla.getText() + o.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_oActionPerformed

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        pantalla.setText(pantalla.getText() + q.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_qActionPerformed

    private void eneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eneActionPerformed
        pantalla.setText(pantalla.getText() + ene.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_eneActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        pantalla.setText(pantalla.getText() + f.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        pantalla.setText(pantalla.getText() + h.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_hActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        pantalla.setText(pantalla.getText() + a.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        pantalla.setText(pantalla.getText() + l.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_lActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        pantalla.setText(pantalla.getText() + k.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_kActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        pantalla.setText(pantalla.getText() + d.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void dospuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dospuntosActionPerformed
 pantalla.setText(pantalla.getText() + dospuntos.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_dospuntosActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
            pantalla.setText(pantalla.getText() + s.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_sActionPerformed

    private void comillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comillasActionPerformed
 pantalla.setText(pantalla.getText() + comillas.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_comillasActionPerformed

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        pantalla.setText(pantalla.getText() + j.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_jActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        pantalla.setText(pantalla.getText() + g.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_gActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
         pantalla.setText(pantalla.getText() + punto.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_puntoActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        pantalla.setText(pantalla.getText() + n.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void slashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slashActionPerformed
         pantalla.setText(pantalla.getText() + slash.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_slashActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        pantalla.setText(pantalla.getText() + c.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        pantalla.setText(pantalla.getText() + m.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        pantalla.setText(pantalla.getText() + b.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        pantalla.setText(pantalla.getText() + x.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_xActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        pantalla.setText(pantalla.getText() + v.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_vActionPerformed

    private void interrogacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interrogacionActionPerformed
         pantalla.setText(pantalla.getText() + interrogacion.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_interrogacionActionPerformed

    private void comaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comaActionPerformed
        pantalla.setText(pantalla.getText() + coma.getText()); 
    // TODO add your handling code here:
    }//GEN-LAST:event_comaActionPerformed

    private void zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zActionPerformed
        pantalla.setText(pantalla.getText() + z.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_zActionPerformed

    private void shift2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shift2ActionPerformed
      
    // TODO add your handling code here:
    }//GEN-LAST:event_shift2ActionPerformed

    private void ctrl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrl2ActionPerformed
         pantalla.setText(pantalla.getText() + ctrl2.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_ctrl2ActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        pantalla.setText(pantalla.getText() + igual.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_igualActionPerformed

    private void altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altActionPerformed
        pantalla.setText(pantalla.getText() + alt.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_altActionPerformed

    private void alt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt2ActionPerformed
         pantalla.setText(pantalla.getText() + alt2.getText());       
    // TODO add your handling code here:
    }//GEN-LAST:event_alt2ActionPerformed

    private void puntoycomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoycomaActionPerformed
        pantalla.setText(pantalla.getText() + puntoycoma.getText());        
    // TODO add your handling code here:
    }//GEN-LAST:event_puntoycomaActionPerformed

    private void spacebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spacebarActionPerformed
        pantalla.setText(pantalla.getText() + " "); 
        
    }//GEN-LAST:event_spacebarActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
         pantalla.setText(pantalla.getText() + "\n" );
    // TODO add your handling code here:
    }//GEN-LAST:event_enterActionPerformed

    private void derechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechaActionPerformed
         pantalla.setText(pantalla.getText() + derecha.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_derechaActionPerformed

    private void abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abajoActionPerformed
         pantalla.setText(pantalla.getText() + abajo.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_abajoActionPerformed

    private void izquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierdaActionPerformed
         pantalla.setText(pantalla.getText() + izquierda.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_izquierdaActionPerformed

    private void arribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arribaActionPerformed
        pantalla.setText(pantalla.getText() + arriba.getText());
    // TODO add your handling code here:
    }//GEN-LAST:event_arribaActionPerformed

    private void mayusculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mayusculasMouseClicked
  if(evt.getClickCount()==2){ 
   a.setText("a");
   b.setText("b"); 
   c.setText("c"); 
   d.setText("d"); 
   e.setText("e"); 
   f.setText("f"); 
   g.setText("g"); 
   h.setText("h"); 
   i.setText("i"); 
   j.setText("j"); 
   k.setText("k"); 
   l.setText("l"); 
   m.setText("m"); 
   n.setText("n"); 
   o.setText("o"); 
   p.setText("p"); 
   q.setText("q"); 
   r.setText("r"); 
   s.setText("s"); 
   t.setText("t"); 
   u.setText("u"); 
   v.setText("v"); 
   w.setText("w"); 
   x.setText("x"); 
   y.setText("y"); 
   z.setText("z"); 
   
  }  
  
  if(evt.getClickCount()==1){
   a.setText("A");
   b.setText("B"); 
   c.setText("C"); 
   d.setText("D"); 
   e.setText("E"); 
   f.setText("F"); 
   g.setText("G"); 
   h.setText("H"); 
   i.setText("I"); 
   j.setText("J"); 
   k.setText("K"); 
   l.setText("L"); 
   m.setText("M"); 
   n.setText("N"); 
   o.setText("O"); 
   p.setText("P"); 
   q.setText("Q"); 
   r.setText("R"); 
   s.setText("S"); 
   t.setText("T"); 
   u.setText("U"); 
   v.setText("V"); 
   w.setText("W"); 
   x.setText("X"); 
   y.setText("Y"); 
   z.setText("Z");    
  } 
    
// TODO add your handling code here:
    }//GEN-LAST:event_mayusculasMouseClicked

    private void shiftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shiftMouseEntered
       
        // TODO add your handling code here:
    }//GEN-LAST:event_shiftMouseEntered

    private void shiftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shiftMouseClicked
       if(evt.getClickCount()==1){ 
   a.setText("a");
   b.setText("b"); 
   c.setText("c"); 
   d.setText("d"); 
   e.setText("e"); 
   f.setText("f"); 
   g.setText("g"); 
   h.setText("h"); 
   i.setText("i"); 
   j.setText("j"); 
   k.setText("k"); 
   l.setText("l"); 
   m.setText("m"); 
   n.setText("n"); 
   o.setText("o"); 
   p.setText("p"); 
   q.setText("q"); 
   r.setText("r"); 
   s.setText("s"); 
   t.setText("t"); 
   u.setText("u"); 
   v.setText("v"); 
   w.setText("w"); 
   x.setText("x"); 
   y.setText("y"); 
   z.setText("z"); 
   
  }  
        // TODO add your handling code here:
    }//GEN-LAST:event_shiftMouseClicked

    private void shift2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shift2MouseClicked
     if(evt.getClickCount()==1){ 
   a.setText("a");
   b.setText("b"); 
   c.setText("c"); 
   d.setText("d"); 
   e.setText("e"); 
   f.setText("f"); 
   g.setText("g"); 
   h.setText("h"); 
   i.setText("i"); 
   j.setText("j"); 
   k.setText("k"); 
   l.setText("l"); 
   m.setText("m"); 
   n.setText("n"); 
   o.setText("o"); 
   p.setText("p"); 
   q.setText("q"); 
   r.setText("r"); 
   s.setText("s"); 
   t.setText("t"); 
   u.setText("u"); 
   v.setText("v"); 
   w.setText("w"); 
   x.setText("x"); 
   y.setText("y"); 
   z.setText("z"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_shift2MouseClicked
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton abajo;
    private javax.swing.JButton alt;
    private javax.swing.JButton alt2;
    private javax.swing.JButton arriba;
    private javax.swing.JButton b;
    private javax.swing.JButton borrar;
    private javax.swing.JButton c;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton coma;
    private javax.swing.JButton comillas;
    private javax.swing.JButton ctrl;
    private javax.swing.JButton ctrl2;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton d;
    private javax.swing.JButton derecha;
    private javax.swing.JButton dos;
    private javax.swing.JButton dospuntos;
    private javax.swing.JButton e;
    private javax.swing.JButton ene;
    private javax.swing.JButton enter;
    private javax.swing.JButton esc;
    private javax.swing.JButton esclamacion;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton igual;
    private javax.swing.JButton interrogacion;
    private javax.swing.JButton izquierda;
    private javax.swing.JButton j;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton m;
    private javax.swing.JButton mayusculas;
    private javax.swing.JButton n;
    private javax.swing.JButton nueve;
    private javax.swing.JButton o;
    private javax.swing.JButton ocho;
    private javax.swing.JButton p;
    private javax.swing.JTextArea pantalla;
    private javax.swing.JButton parentesis;
    private javax.swing.JButton parentesis2;
    private javax.swing.JButton punto;
    private javax.swing.JButton puntoycoma;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton resta;
    private javax.swing.JButton s;
    private javax.swing.JButton seis;
    private javax.swing.JButton shift;
    private javax.swing.JButton shift2;
    private javax.swing.JButton siete;
    private javax.swing.JButton slash;
    private javax.swing.JButton spacebar;
    private javax.swing.JButton suma;
    private javax.swing.JButton t;
    private javax.swing.JButton tabulador;
    private javax.swing.JButton tres;
    private javax.swing.JButton u;
    private javax.swing.JButton uno;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables
}
